### ISSUE TITLE
question about _fillvalue

### ISSUE THREAD

**Issue by liuzhenyuan18** [trondkr/model2roms#11]
In this project , I have many  missing values and how can I filling it??Will they affect ROMS mode operation?

**Comment by liuzhenyuan18** [comment]
I modified the scripts and used my own  daily data  to run it , but I didn‘t know how to fill the missing values

**Comment by trondkr** [comment]
You need to identify what the missing_value in your daily data is. Usually, it is a very large number (e.g. 1e30) but it. should be obvious when you do a `ncdump -h` of your file. Next set the value in `configM2R.py` to that value so that all values in your original data are correctly masked by model2roms when you run the scripts. Look for `self.fillvaluein = -1.e20` in configM2R.py

**Comment by liuzhenyuan18** [comment]
I downloaded the original data from HYCOM , but the "_fillvalue" covering all my grid area. so when I used it to interpolate to the ROMS‘s grid, it’s  "_fillvalue"  too. I tried solve this problem by using the griddata  method to fill the “_fillvalue”  firstly, and then made the interpolate . The script is modified as follows ：

def dohorinterpolationregulargrid(confM2R, mydata, myvar):
    if confM2R.showprogress is True:
        try:
            import progressbar
            widgets=['\rHorizontal interpolation:', progressbar.Percentage(), progressbar.Bar()]
            progress = progressbar.ProgressBar(confM2R.grdMODEL.nlevels, widgets=widgets).start()
        except ImportError:
            print("Could not find module progressbar")
            confM2R.showprogress=False
        pass

    indexROMS_Z_ST, toxi, toeta, mymask = setupIndexes(confM2R, myvar)#
    array1 = np.zeros((indexROMS_Z_ST), dtype=np.float)#
    # 2D or 3D interpolation
    depthlevels=confM2R.grdMODEL.nlevels
    if myvar in ['ssh', 'ageice', 'uice', 'vice', 'aice', 'hice', 'snow_thick','hs']:
        depthlevels=1
    for k in range(depthlevels):
        if confM2R.useesmf:
            if depthlevels==1:
                indata=np.squeeze(mydata[:, :])
            else:
                indata=np.squeeze(mydata[k, :, :])
            ##################################
            LON=confM2R.grdMODEL.lon #
            LAT=confM2R.grdMODEL.lat #
            ddata=np.array(indata[:,:]).reshape(-1)
            dlon=np.array(LON).reshape(-1)
            dlat=np.array(LAT).reshape(-1)
            ddata2=ddata[~np.isnan(ddata)]
            dlon2=dlon[~np.isnan(ddata)]
            dlat2=dlat[~np.isnan(ddata)]
            dlatlon2=np.array([dlat2,dlon2]).T 
            indata = griddata(dlatlon2, ddata2, (LAT, LON), method='nearest')
          #######################################
            # We interpolate to RHO fields for all variables and then we later interpolate RHO points to U and V points
            # But input data are read on U and V and RHO grids if they differ (as NorESM and GLORYS does).
            if myvar in ['uice','uvel']:
                confM2R.grdMODEL.fieldSrc_u.data[:, :] = np.flipud(np.rot90(indata))
                field = confM2R.grdMODEL.regridSrc2Dst_u(confM2R.grdMODEL.fieldSrc_u, confM2R.grdMODEL.fieldDst_rho)
            elif myvar in ['vice','vvel']:
                confM2R.grdMODEL.fieldSrc_v.data[:, :] = np.flipud(np.rot90(indata))
                field = confM2R.grdMODEL.regridSrc2Dst_v(confM2R.grdMODEL.fieldSrc_v, confM2R.grdMODEL.fieldDst_rho)
            else:
     
                confM2R.grdMODEL.fieldSrc_rho.data[:, :] = np.flipud(np.rot90(indata))#
                field = confM2R.grdMODEL.regridSrc2Dst_rho(confM2R.grdMODEL.fieldSrc_rho, confM2R.grdMODEL.fieldDst_rho)




Is this reasonable? 
thanks

**Comment by trondkr** [comment]
It is really hard to say what you are doing here actually. I do not understand why the HYCOM data would have fill value everywhere. Does your results look okay after your masking? Can you post some images of your data and the result after your masking?

**Comment by liuzhenyuan18** [comment]
I have sent the data and pictures to your mailbox, the following is the data link：
https://1drv.ms/u/s!Ag_l6dRC2F2tajLEj3boRoaG0jE

HYCOM_Y2016M9D16.nc is the original HYCOM data and ROMs_grd.nc is my grid file.
In the 0-75 meters, the data is normal.  but the deeper ,  the more "_fillvalue".
By using the data after "griddata"  ,I have successfully run ROMS and It looks normal. But I don’t know wether this method is reasonable

**Comment by liuzhenyuan18** [comment]
Hi，Thanks for your response .The current scripts can accept the Z coordinate system, but I need to use the model data as the forcing for ROMs (just like CESM output with S vertical coordinate) . What should I do? Look forward to your suggestion.

**Comment by trondkr** [comment]
Do you mean that you have forcing files on sigma coordinates and you want to use these as input to model2roms? If so, as you mentioned model2roms requires forcing files on z-levels so you will have to 1) convert your forcing to z-levels or 2) add functionality to model2roms to be able to read and process sigma coordinates. The latter would be great to get help to implement and it should not be difficult but everything takes time. If you want to convert the ROMS files to z-level you can use an old toolbox I have here https://github.com/trondkr/romstools/tree/master/Postpro . I have not used it in a few years but should be able to convert your data.

Also see here: https://github.com/trondkr/romstools

**Comment by liuzhenyuan18** [comment]
Thank you so much for your reply .  I'll try that.

**Comment by liuzhenyuan18** [comment]
Hi,Sorry to bother you again .
I have another ncfiles with Monthly average (like pop_ocn1.h.2001-01.nc , pop_ocn1.h.2001-02.nc, pop_ocn1.h.2001-03.nc ) and this nc files  similar to SODA3_5DAY datas with only one time in one file. I have made the init and boundary  successfully , but don't know  how to use it to run ROMs .
what frequency can ROMs  accepte ?
if the init\bry\clim  is monthly average ,What frequency does the weather forcing field（made by ERA5）needed？6 hour? day? or monthly is ok?

**Comment by trondkr** [comment]
@liuzhenyuan18 Sorry for my late reply. ROMS can accept any frequency to the input data. The frequency for atmospheric forcing should be 6 hours to make sure that the kinetic energy driving mixing between the atmosphere and ocean is preserved. If you have longer atmospheric forcing the fields will be more smooth and you lose a lot of the bursts from wind and the extremes which are important to mixing.

**Comment by trondkr** [comment]
Closing this issue as it seems not an issue related to coding bugs etc.

**Comment by liuzhenyuan18** [comment]
Thanks for taking time to answer my questions, I have solved these problems. Again, I really appreciate your kindness.
















At 2021-04-01 23:38:15, "Trond Kristiansen" ***@***.***> wrote:

@liuzhenyuan18 Sorry for my late reply. ROMS can accept any frequency to the input data. The frequency for atmospheric forcing should be 6 hours to make sure that the kinetic energy driving mixing between the atmosphere and ocean is preserved. If you have longer atmospheric forcing the fields will be more smooth and you lose a lot of the bursts from wind and the extremes which are important to mixing.
