### ISSUE TITLE
interp2D fill_value

### ISSUE THREAD

**Issue by jmralves** [trondkr/model2roms#13]
Hello Trond

I am having an issue with the fill_value of GLORYS (-32767). More exactly in interp2D.py
where the 2D interpolation is done

field = confM2R.grdROMS.regridSrc2Dst_rho(confM2R.grdMODEL.fieldSrc_rho, confM2R.grdROMS.fieldDst_rho)

I noted that the input array has the correct fill_value, but the interpolation is made considering the fill_value cells which affect the interpolation output.

I set the fill value in configM2R.py
self.fillvaluein = -32767

I have also made a try with SODA3 reanalysis and in that case M2R worked correctly.

I noted that SODA3 has the Fillvalue and the missing_value attributes, but the GLORYS only has a Fillvalue attribute. For that reason, I added the missing_value attribute to the GLORYS file, but that did not make any effect. 

Do you have any hint to solve the fill_value issue in interp2D.py  with  GLORYS12V1?
 
Best Regards,
José

**Comment by trondkr** [comment]
Could you prove some more info as to what goes wrong? How are the results affected by this? Any plots would’ve helpful. Thanks

**Comment by jmralves** [comment]
![zeta_soda](https://user-images.githubusercontent.com/3593247/115047299-4c92b000-9ed0-11eb-8833-fc311f54f6b4.jpg)
![zeta_glorys](https://user-images.githubusercontent.com/3593247/115047376-5ddbbc80-9ed0-11eb-87b8-dcea1604baec.jpg)

The first figure is made with  SSH from SODA3 for a ROMS domain in the NW African coast. In the figure it is not possible to see the SSH values because of the fill values over land (1.e+20), but the sea SSH values are correct.

In the second figure I show the same domain with SSH from GLORYS12V1. This figure has the GLORYS fill value (-32767) almost everywhere. This seems to occur due to an error that occurs in 2D interpolation.

**Comment by trondkr** [comment]
I have not been able to test this but it seems the setting for reading the in data uses the grdROMS.fillvalue instead of the fillvaluein :
data = np.where(data.mask, confM2R.fillval, data)


Try to edit this to your model2roms.py file and see if it makes a difference.

if confM2R.ocean_indata_type == "SODA3":
   data = cdf.variables[confM2R.input_varnames[varN]][month - 1, :, :, :]
   data = np.where(data.mask, confM2R.fillval, data)

if confM2R.ocean_indata_type == "NORESM":
   # For NorESM data - all data is in one big file so we need the timecounter to access correct data
   myunits = cdf.variables[str(confM2R.input_varnames[varN])].units
   data = np.squeeze(cdf.variables[str(confM2R.input_varnames[varN])][timecounter, :, :, :])
   data = np.where(data.mask, confM2R.fillval, data)

if confM2R.ocean_indata_type == "GLORYS":
   myunits = cdf.variables[str(confM2R.input_varnames[varN])].units
   data = np.squeeze(cdf.variables[str(confM2R.input_varnames[varN])][0, :, :, :])
   data = np.where(data.mask, confM2R.fillval, data)


The thing is that netcdf should automatically mask this so I am not sure why it is not working correctly. I will look more careful in a week when back from work travel. T

**Comment by jmralves** [comment]
Hi Trond 

Thanks for your response, but your suggestion didn’t work for me.

I also tried to add src_mask_values=numpy.array([-32767])
in the last lines of interp2D.py, more exactly here:

confM2R.grdMODEL.regridSrc2Dst_rho = ESMF.Regrid(confM2R.grdMODEL.fieldSrc_rho, confM2R.grdMODEL.fieldDst_rho, **src_mask_values=numpy.array([-32767])**,regrid_method=ESMF.RegridMethod.BILINEAR,unmapped_action=ESMF.UnmappedAction.IGNORE)

but that didn’t work either.

**Comment by trondkr** [comment]
Could you send me a link to your grid file? I can test how its working on my end.

**Comment by jmralves** [comment]
Hi Trond,


The file roms12_9km.nc it's here:

https://www.transfernow.net/dl/202104234YCzqjuT

[https://www.transfernow.net/assets/dist/img/share/sharedl.jpg]<https://www.transfernow.net/dl/202104234YCzqjuT>

Download - TransferNow<https://www.transfernow.net/dl/202104234YCzqjuT>
www.transfernow.net
Download your files now with TransferNow.net, the simple and free service for sending and sharing large files.




I am convinced that the problem is not with the ROMS grid, because just changing from GLORYS to SODA in configM2R.py is enough to obtain the correct bry and ini files.


Regards,

José

________________________________
De: Trond Kristiansen ***@***.***>
Enviado: 23 de abril de 2021 01:06:59
Para: trondkr/model2roms
Cc: José Miguel Alves; Author
Assunto: Re: [trondkr/model2roms] interp2D fill_value (#13)


Could you send me a link to your grid file? I can test how its working on my end.

**Comment by trondkr** [comment]
Hi,

With the current version on model2roms on Github and GLORYS12V1 as input I could create bry, init, and clim file using your grid and the result looks good.

https://www.dropbox.com/s/hf0kcwpud4uwqga/Jos%C3%A8_init_GLORYS_19930115_to_19930531.nc?dl=0

https://www.dropbox.com/s/83cxr75vimaw9mu/Jos%C3%A8_clim_GLORYS_19930115_to_19930531.nc?dl=0


Here is an example of zeta values:


Could you try to run it again using the latest code and let me know how it goes?

Cheers, Trond

**Comment by jmralves** [comment]
Good to know that M2R works with Glorys12V1. But I continue with problems, as you can see in the attached image, of the zeta variable.

Just to be sure that we are using the same GLORYS file. Are you getting the GLORYS file from resources.marine.copernicus.eu?
https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=GLOBAL_REANALYSIS_PHY_001_030
CMEMS<https://resources.marine.copernicus.eu/?option=com_csw&view=details&product_id=GLOBAL_REANALYSIS_PHY_001_030>
resources.marine.copernicus.eu
Joomla! - le portail dynamique et systÃ¨me de gestion de contenu



I am wondering if we are using the same Glorys files, because the one that I am downloading has time units: “hours since 1950-01-01” and in M2R you have 1948 as the reference year, for time units.



José

________________________________
De: Trond Kristiansen ***@***.***>
Enviado: 24 de abril de 2021 00:09:38
Para: trondkr/model2roms
Cc: José Miguel Alves; Author
Assunto: Re: [trondkr/model2roms] interp2D fill_value (#13)


Hi,

With the current version on model2roms on Github and GLORYS12V1 as input I could create bry, init, and clim file using your grid and the result looks good.

https://www.dropbox.com/s/hf0kcwpud4uwqga/Jos%C3%A8_init_GLORYS_19930115_to_19930531.nc?dl=0

https://www.dropbox.com/s/83cxr75vimaw9mu/Jos%C3%A8_clim_GLORYS_19930115_to_19930531.nc?dl=0


Here is an example of zeta values:


Could you try to run it again using the latest code and let me know how it goes?

Cheers, Trond

**Comment by trondkr** [comment]
Hi,

Yes I use the same file or reanalysis as you link to. I use 1948 as reference date for what I write to file (not what I read). Model2roms uses the filename to identify the month and year (this will change soon) so we don’t actually use he time units in the file. I am not sure what goes wrong with your code as my zeta calculations works fine using your grid file. Did you use the latest version on Github of M2R? Can you try to open the result file in Panoply to make sure it looks strange in another program than what you are using? T


Cheers, Trond

**Comment by trondkr** [comment]
I should also mention that the GLORYS time units and calendar are read directly from file and used to convert the date into Julian day since 1948-1-1 (in model2roms.py):
if confM2R.ocean_indata_type == 'GLORYS':
   # Find the day and month that the GLORYS file represents based on the year and ID number.
   # Each file represents a 1 month average.
   calendar = cdf.variables["time"].calendar
   units = cdf.variables["time"].units
   currentdate = datetime(year, month, day)
   jd = date2num(currentdate, units, calendar=calendar)



Cheers, Trond

**Comment by jmralves** [comment]
Yes, I am using the latest version on Github of M2R.

Please, tell me which version of ESMPY are you using.


José

________________________________
De: Trond Kristiansen ***@***.***>
Enviado: 27 de abril de 2021 01:01:58
Para: trondkr/model2roms
Cc: José Miguel Alves; Author
Assunto: Re: [trondkr/model2roms] interp2D fill_value (#13)


Hi,

Yes I use the same file or reanalysis as you link to. I use 1948 as reference date for what I write to file (not what I read). Model2roms uses the filename to identify the month and year (this will change soon) so we don’t actually use he time units in the file. I am not sure what goes wrong with your code as my zeta calculations works fine using your grid file. Did you use the latest version on Github of M2R? Can you try to open the result file in Panoply to make sure it looks strange in another program than what you are using? T


Cheers, Trond

**Comment by trondkr** [comment]
I am using ESMF 8.1.1 (latest) but I don’t think  anything has changed with those methods used in M2R.

https://anaconda.org/conda-forge/esmf

So you download Glory’s directly from Copernicus or do you process them somehow? Could any step go wrong prior to running M2R?

Cheers, Trond

**Comment by jmralves** [comment]
Yes, I download Glorys directly from Copernicus.

I was able to create the correct init and bry files from Glorys when I download all Glorys domain, but that is not practical for me. Shouldn’t M2R work when I use a subdomain of Glorys?


________________________________
De: Trond Kristiansen ***@***.***>
Enviado: 28 de abril de 2021 15:16:26
Para: trondkr/model2roms
Cc: José Miguel Alves; Author
Assunto: Re: [trondkr/model2roms] interp2D fill_value (#13)


I am using ESMF 8.1.1 (latest) but I don’t think  anything has changed with those methods used in M2R.

https://anaconda.org/conda-forge/esmf

So you download Glory’s directly from Copernicus or do you process them somehow? Could any step go wrong prior to running M2R?

Cheers, Trond

**Comment by jmralves** [comment]
Yes, I download Glorys directly from Copernicus.

I was able to create the correct init and bry files from Glorys when I download all Glorys domain, but that is not practical for me. Shouldn’t M2R work when I use a subdomain of Glorys?

**Comment by trondkr** [comment]
Just checking back in with you to see if you fixed your issue. I just pushed a new commit to Github of model2roms that fixes a problem with the time units for GLORYS that I believe you also experienced. 

Regarding, interpolation of subsets of data, that should work fine. Do you still have an issue and if so would you mind posting some code and error messages so I can debug?

**Comment by trondkr** [comment]
Closing this issue as it seems resolved? Feel free to reopen if not. T
