### ISSUE TITLE
Fill Value calculation seems off 

### ISSUE THREAD

**Issue by tommy307507** [trondkr/model2roms#14]
I am using HYCOM data as input for my ROMS domain and I have a different landmask than the HYCOM grid, thus needing to fill quite a number of spots
I am using the laplace filter and fill.f90 on every regular level of my HYCOM data after interpolating it to rho grid like in the function do_hor_interpolation_regular_grid, however I found the result to be worse than my naive nearest neighbor filling and when I checked the ini files it fills in weird values that's 10 degrees colder than the surranding data points... thus causing the ROMS to blow up very early ...
![image](https://user-images.githubusercontent.com/49487505/133711722-49f765d6-9b26-4cfc-a892-32d15ed19682.png)
the deepgreen color points are around 16 degrees while the majority of data here is 28 degrees C

Am I using the code wrong or is this the intended behaviour of the filling algorithm? 

DISCLAIMER: I am using my own version of code to download and interpolate this to the 2d grid and only using the fill.f90 and laplace filter as a test to see if I can do better in filling...

**Comment by trondkr** [comment]
I am on travels so will have to look into this in more detail later on so this is just a quick reply. I am not sure what is happening here - obviously the big difference in temperature seems wrong. Is there any way your code is using the fill_value to interpolate to? Can you make sure you are using a proper mask value?

I have converted completely to using xesmf (v. 8.0.1 and higher) where you can now do extrapolation using ESMF. This is a very good alternative to using the fill.f90 routine which is very old. I will update model2roms  to use xesmf and extrapolation when I have some extra time. Here is a quick example of how you submit an input dataset (using xarray.Dataset) and an output dataset and interpolate with extrapolation using xesmf (import xesmf as xe):
def add_matrix_nans(self, r):
   """Deal with wrong boundary
   :param r:
   :return:
   """
   X = r.weights
   M = scipy.sparse.csr_matrix(X)
   num_nonzeros = np.diff(M.indptr)
   M[num_nonzeros == 0, 0] = np.NaN
   r.weights = scipy.sparse.coo_matrix(M)

   return r

regridder = xe.Regridder(ds_in, ds_out,
                        "bilinear",
                        extrap_method='inverse_dist',
                        extrap_num_src_pnts=8,
                        extrap_dist_exponent=2,
                        ignore_degenerate=True)
                      #  unmapped_to_nan=True)

regridder = sdutils.add_matrix_nans(regridder)
return regridder(ds_in)

Let me know if this helps. Happy to look more into this later. T

**Comment by tommy307507** [comment]
I think it's because I didnt mask my landmask as invalid that caused it to fill in the weird values....
Doing the flooding of the whole domain and then using the fill code works just fine from my testing 
I might look into using ESMF later if this ended up making ROMS upset and thanks for your input :)

p.s. I found your project weeks after I converted all of COAWST's ROMS matlab scripts into python manually ... seems its the most active so far , keep up the good work xD

**Comment by trondkr** [comment]
Great to hear things worked out. Ill close this issue as it seems resolved.
