### ISSUE TITLE
Tcline in class s_coordinate(object):

### ISSUE THREAD

**Issue by alicebarthel** [trondkr/model2roms#3]
Hi Trond, 
Just letting you know there was a bug when I changed the target grid to mine (rather than roho800). The problem was that the class s_coordinate(object) had Tcline defined as a attribute, while it is called (and defined elsewhere) as tcline. 
I've changed Tcline to tcline everywhere to be safe, but I think the only real problem was with the attribute definition. You can either update it yourself or I'll include it in my next pull request.

**Comment by trondkr** [comment]
Fixed
