### ISSUE TITLE
Thanks for the Fix for python3.7: error in compiling interpolation.f90

### ISSUE THREAD

**Issue by dhirendrajnu** [trondkr/model2roms#4]
Hii there
 I was having a problem with the compilation of interpolation.f90 and it crashed with the following error

Compiling barotropic.f90 to create ==> barotropic.so
Compiling interpolation.f90 to create ==> interpolation.so
error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -I/tmp/tmpbuss0hc2/src.linux-x86_64-3.7 -I/opt/apps/ANACONDA/lib/python3.7/site-packages/numpy/core/include -I/opt/apps/ANACONDA/include/python3.7m -c -c /tmp/tmpbuss0hc2/src.linux-x86_64-3.7/interpolation-f2pywrappers2.f90 -o /tmp/tmpbuss0hc2/tmp/tmpbuss0hc2/src.linux-x86_64-3.7/interpolation-f2pywrappers2.o -J/tmp/tmpbuss0hc2/ -I/tmp/tmpbuss0hc2/" failed with exit status 1
Compiling fill.f90 to create ==> extrapolate.so
Compilation finished and results written to file => compile.log

As per your suggestion, I used 

**export LDFLAGS="-undefined dynamic_lookup -bundle"
f2py -c -m interpolation interpolation.f90**

and it worked perfect.

Thanks for updating the LDFLAG fix for python3.7.  I was not on github previously so I did not update this issue previously.

Thanks again.

**Comment by trondkr** [comment]
Great that everything is working!
