### ISSUE TITLE
issues with running model2roms

### ISSUE THREAD

**Issue by jkansong** [trondkr/model2roms#8]
Hi,

(1) Thanks for your efforts in writing model2roms. I'm trying to use it but I had the following error about the absence of module called 'extrapolate'. I was wondering whether you forgot to include it in the package. 

exec(open('runM2R.py').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "/home/jkansong/model2roms/model2roms.py", line 5, in <module>
    import interp2D
  File "/home/jkansong/model2roms/interp2D.py", line 4, in <module>
    import extrapolate as ex
ModuleNotFoundError: No module named 'extrapolate'

(2) In runM2R.sh (and also in the README) you have a script called 'main.py' but I can't find this in the package. By the way, I used git to clone model2roms to my Ubuntu system. I don't know if that's the reason.

(3) Inside configM2R.py you have the following code snippet to grab a subset of, say global, data. But it's not clear to me what the numbers are. Are they the latitudes  and longitudes of the region to subset? If so, which ones a latitudes and which are longitudes. It's also more confusing because the indices in subset are not consistent for NS8KM versus A20.
 if self.outgrid == "NS8KM":
            subset[1] = 40
            subset[1] = 70
            subset[2] = -30
            subset[3] = 40

        if self.outgrid == "A20":
            subset[0] = 30
            subset[1] = 90
            subset[2] = -179
            subset[3] = 360

(4) It'll be helpful if you could provide a minimal example of how to run model2roms. 

Thanks very much!

-Joseph K. Ansong

**Comment by trondkr** [comment]
Hi,

1. The quick answer is that you have to compile the Fortran files using the
compile.py script. You need to have fortran compiler installed and edit
compile.py. Then you run: python compile.py for f2py to do its magic. 

2. Main.py is obsolete and not used anymore so ignore that (I need to update the docs. Use runM2R.py for running model2roms and delete main.py.

3. So the subset refers to subset[0]=min_lon, subset[1]=max_lon, subset[2]=min_lat,subset[3]=max_lat. The reason these differ between grids is that the NS8KM is an old ROMS model I have for the North Sea (check lats and lons). The A20 model is a huge ROMs model that covers the entire northern hemisphere from 30N.

Hope this helps.

**Comment by jkansong** [comment]
Thanks for the quick response; I'll try that. I've also updated my comments and added a few more issues. Thanks again.

**Comment by jkansong** [comment]
> 
> Hi, 1. The quick answer is that you have to compile the Fortran files using the compile.py script. You need to have fortran compiler installed and edit compile.py. Then you run: python compile.py for f2py to do its magic. 2. Main.py is obsolete and not used anymore so ignore that (I need to update the docs. Use runM2R.py for running model2roms and delete main.py. 3. So the subset refers to subset[0]=min_lon, subset[1]=max_lon, subset[2]=min_lat,subset[3]=max_lat. The reason these differ between grids is that the NS8KM is an old ROMS model I have for the North Sea (check lats and lons). The A20 model is a huge ROMs model that covers the entire northern hemisphere from 30N. Hope this helps.
